### ISSUE TITLE
Error stat()ing: ./emacs.d/lisp

### ISSUE THREAD

**Issue by manuel-uberti** [syohex/emacs-helm-ag#147]
I just grabbed latest helm-ag from MELPA. I am using Emacs 25.0.50.1, built from latest sources a couple of hours ago.

If I try to look for a string in my ~/.emacs.d/lisp directory, this is what ```*helm-ag*``` buffer shows:
```
ERR: Error stat()ing: .emacs.d/lisp
ERR: Error opening directory .emacs.d/lisp: No such file or directory
```
The directory exists, and I can call find-name-dired on it with no problem.

I get the same error trying with a different directory too.

If you need me to do other tests to help nailing down the issue, feel free to ask.

**Comment by manuel-uberti** [comment]
As stated [here](https://github.com/bbatsov/projectile/issues/821#issuecomment-125677683), it is enough to require grep in my init.el before helm-ag:
```
(require 'grep)
```

**Comment by manuel-uberti** [comment]
Apparently, that is not enough. I had to issue ```helm-projectile-ag``` before ```helm-ag``` before having the latter working with no error.

**Comment by manuel-uberti** [comment]
I did other tests: the problem was introduced by [this commit](https://github.com/syohex/emacs-helm-ag/commit/b2f00435e85fc5ab8f6d2118b621bd672e5b2c5a).

**Comment by syohex** [comment]
I cannot reproduce this issue. Would you tell me how to reproduce this issue in more detail ?

**Comment by manuel-uberti** [comment]
Sure:

- start Emacs
- on my config *scratch* buffer is the first thing that I see when Emacs is loaded
- issue ```helm-do-ag```
- navigate to ```/home/manuel/.emacs.d/lisp``` and hit ```RET```
- write the pattern I am looking for: ```disabled```

Those errors appear in *helm-ag* buffer.

**Comment by syohex** [comment]
I can reproduce. I'll try to fix.

**Comment by syohex** [comment]
I have fixed at #148. Please check latest version.

**Comment by manuel-uberti** [comment]
Thank you, it is working now.

**Comment by hubgitname** [comment]
I still see this issue in 2019. helm-ag is fine, helm-projectile-ag has this problem.
